### ISSUE TITLE
Add "Acessibilidade" link to Campaign page

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist-platform#888] opened 2018-05-18 20:30 UTC
1.  Add link "Acessibilidade" (accessibility) on Campaign Page between “Temas e Palavras-chaves” and "FAQ"

=>  Saiba mais   /   Temas e Palavras-chaves   /   Acessibilidade   /   FAQ

http://unasus.unifesp.br/comunicados/FAQ_AppCivist/Acessibilidade.html

2.  Add the Wheelchair Symbol just before word "Acessibilidade":

![download](https://user-images.githubusercontent.com/5572598/40256425-c9ced8ac-5ac0-11e8-9d44-139a7ab41fbd.png)

**Comment by cdparra** [comment] 2018-05-23 19:29
Closing as this is now a duplicate of #901 and appcivist-pb-client#1176

**Closed by cdparra** 2018-05-23 19:29 UTC
Labels: Priority: High, Type: Enhancement, duplicate
